token:
  expiration_time: 86400000 # 만료기간 1일
  secret: '{cipher}AQAJzmpTInWfT5LhaHrnao7ZQ/Y24MkT1aulSTc6KcnEDfsdlJyWuNQwma66IHUOJl+EF5XJwgZYC0k/33wP7Ia4uLMQLD27Zpvi2cEYMK81TFOhPHt7ObsGXBAFlTbVhgPJ0Y3aK5lqy7+LuTLfiCrzvzBv0oHsBOwKtHP8KdNqjhgLRA0MF4X+Xruw6W++LxiPsYZO/0F0L8LfeH1eVExeZ7m3yMFE28Mg20LWh/CQWas2iDig1Efq1PFTTZeX9+30TMiLY02LHYTfpviU3l6upmy7MJJ/49sIg+1jBvjcFzLHEBjcXYy4L8OFfXyxUQMGxqTSj/cbSWsNqSYPMZJZrkfFoIyPFwOjzIYde6gielPumb50NPqvABUe+bqW4WTc+Ht0fqEvbz335NNbzIlKcOzWIiuMUNClicqyK+QWIdFyMuVBb0CtboNAXGL2B6MS+X+5zd6KKJcnXWMLejZuM4XlxJDCU7aEwdfYLDJc5A=='

gateway:
  ip: 192.168.0.1