server:
  port: 8888

spring:
  application:
    name: config-service

  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: guest
    password: guest

  profiles:
    active: native
  cloud:
    config:
      server:
        native:
          search-locations: file:///D:\spring-cloud\native-file-repo
        git:
          uri: https://github.com/padosol/spring-cloud-config
#          username: [your username]
#          password: [your password]
#          uri: file:///D:\spring-cloud\git-local-repo

management:
  endpoints:
    web:
      exposure:
        include: health, busrefresh

encrypt:
#  key: wqkrt;ljqwlkrjwqklcrjw439450283490238402  # 대칭키 방식
  key-store:
    location: file:///D:\spring-cloud\key-store/apiEnctryptionKey.jks
    password: test1234
    alias: apiEncryptionKey


